title: "Hebe's Blog"
author: "Hebe Hilhorst"
description: "Random ramblings"
more: "read more »"
url: "http://localhost:4000"
# baseurl: "http://localhost:4000"
paginate: 8
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - github: "https://github.com/HebeHH"
  - envelope: "mailto:hebehh@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
